version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install npm packages
          command: yarn
      - run:
          name: run jest
          command: yarn test
      - run:
          name: install bundler
          command: gem install bundler:2.2.16
      - run:
          name: install gems
          command: bundle install --jobs 4
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: run test
          command: bundle exec rspec
